version: "3.7"
networks:
    internal:
        ipam:
            driver: default
            config:
              - subnet: 172.20.0.0/24

services:
    redis:
        image: redis:alpine
        restart: always
        networks:
            internal:
                ipv4_address: 172.20.0.100

    node:
        image: rickyhao/ssmgr_docker:latest
        restart: always
        networks:
            internal:
                ipv4_address: 172.20.0.101
        volumes:
          - /home/ricky/.ssmgr:/root/.ssmgr:Z
        depends_on:
          - redis
        command: -c /root/.ssmgr/ss.yml -r libev:chacha20-ietf-poly1305

    webgui:
        image: rickyhao/ssmgr_docker:latest
        restart: always
        networks:
            internal:
                ipv4_address: 172.20.0.102
        volumes:
          - /home/ricky/.ssmgr:/root/.ssmgr:Z
        ports:
          - "8888:8888"
        depends_on:
          - ss
        command: -c /root/.ssmgr/webgui.yml
